services:
  news-ui:
    image: new-ui
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8998:80
    networks:
      - news-network

networks:
  news-network:
    driver: bridge